Import('root_env SOURCE_FILES')

SOURCE_FILES.append(File('SConscript'))

env = root_env.Clone()

env.Alias("install", env.Install("$INCLUDEDIR"))


h_files = map(File, \
    [
     "push.h",
    ])

SOURCE_FILES.extend(h_files)

env.Alias("install", env.Install("$INCLUDEDIR",
                                 h_files))


push_h_files = map(File, \
    [
     "push/eof.h",
     "push/protobuf.h",
     "push/skip.h",
     "push/trash.h",
    ])

SOURCE_FILES.extend(push_h_files)

env.Alias("install", env.Install("$INCLUDEDIR/push",
                                 push_h_files))


protobuf_h_files = map(File, \
    [
     "push/protobuf/basics.h",
     "push/protobuf/field.h",
     "push/protobuf/message.h",
     "push/protobuf/varint32.h",
     "push/protobuf/varint64.h",
    ])

SOURCE_FILES.extend(protobuf_h_files)

env.Alias("install", env.Install("$INCLUDEDIR/push/protobuf",
                                 protobuf_h_files))
